### ISSUE TITLE
Sony RX100 - Download never finishes and thumbnail generation stuck at 4%

### ISSUE THREAD

**Issue by Groberen** [damonlynch/rapid-photo-downloader#105]
OS: Linux Mint 20.3 Cinnamon

A while ago, I noticed a couple of problems started to occur using RPD.

- When downloading completes, it still show "Downloading from disk - A few seconds left (0.0 MB/sec)" in lower left corner, and "98%" in lower right corner. This never changes (I've tested waiting for 2 hours and still it doesn't confirm download complete).
- Also recently, the generation of thumbnails stuck at 4% and never complete.

While those problems exist, I can still use RPD to download photos.
[rpd-bug-report-20230410.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/11194270/rpd-bug-report-20230410.tar.gz)

**Comment by damonlynch** [comment]
@Agilulfo Thanks for picking up that bug with the unexpected keyword argument. I have fixed it just now.

As for the thumbnail generation not completing, can you attach the bug report? That way I will be able to compare it to the report by @Groberen.

**Comment by Agilulfo** [comment]
@damonlynch here is what I've got yesterday.
[rpd-bug-report-20240212.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/14257994/rpd-bug-report-20240212.tar.gz)

**Comment by bweigel** [comment]
> I think I'm having a similar issue with the download getting stuck when trying to download video. In my case I'm downloading them from my sdcard (recorded on a panasonic-g80)
> 
> Some logs of warning level also suggest something is going on with thumbnail genration
> 
> Not sure if related but I've noticed this traceback in the logs ( running the tool with --debug --verbose options)
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 1131, in <module>
>     rename.run()
>   File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 1090, in run
>     move_succeeded = self.process_file(rpd_file, download_count)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 918, in process_file
>     generation_succeeded = self.generate_names(rpd_file, synchronize_raw_jpg)
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 777, in generate_names
>     generate_subfolder(
>   File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 275, in generate_subfolder
>     rpd_file.download_subfolder = _generate_name(
>                                   ^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 237, in _generate_name
>     do_generation = load_metadata(
>                     ^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 202, in load_metadata
>     if rpd_file.metadata is None and not rpd_file.load_metadata(
>                                          ^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: Video.load_metadata() got an unexpected keyword argument 'force_exiftool'
> ```

I had the same issue with version [v0.9.35](https://github.com/damonlynch/rapid-photo-downloader/releases/tag/v0.9.35), but can confirm it has been fixed in [v0.9.36](https://github.com/damonlynch/rapid-photo-downloader/releases/tag/v0.9.36), probably by https://github.com/damonlynch/rapid-photo-downloader/commit/8306992d55a1ea390307a7b272c52f40b2dd8025
