### ISSUE TITLE
Preferences fails to open

### ISSUE THREAD

**Issue by aquada** [damonlynch/rapid-photo-downloader#119]
OS:NixOS unstable
Version: 0.9.34

When opening Preferences (Ctrl-p or menu) a dialog appears stating a problem occurred with RPD

`Traceback (most recent call last):
  File "/nix/store/hap6x8561bnb5d6d1y6f5i9aapaz9s13-rapid-photo-downloader-0.9.34/lib/python3.11/site-packages/raphodo/rapid.py", line 2967, in doPreferencesAction
    dialog = PreferencesDialog(prefs=self.prefs, parent=self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/hap6x8561bnb5d6d1y6f5i9aapaz9s13-rapid-photo-downloader-0.9.34/lib/python3.11/site-packages/raphodo/prefs/preferencedialog.py", line 142, in __init__
    self.chooser = QNarrowListWidget(no_focus_recentangle=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/hap6x8561bnb5d6d1y6f5i9aapaz9s13-rapid-photo-downloader-0.9.34/lib/python3.11/site-packages/raphodo/ui/viewutils.py", line 641, in __init__
    self.setStyle(ProxyStyleNoFocusRectangle())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QProxyStyle(style: typing.Optional[QStyle] = None): not enough arguments
  QProxyStyle(key: str): not enough arguments
`

Log file attached
[rpd-bug-report-20231215.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/13682724/rpd-bug-report-20231215.tar.gz)

**Comment by damonlynch** [comment]
The call to `QProxyStyle()` is 100% valid: https://doc.qt.io/qt-5/qproxystyle.html
That indicates something is wrong with your installation of PyQt5. It might be a build issue with an incompatible version of `sip`, for example. 

It looks like whoever put this package together is responsible for resolving this problem.

**Comment by aquada** [comment]
Thank you, I'll follow up with package maintainers

18 Dec 2023 06:27:44 Damon Lynch ***@***.***>:
