### ISSUE TITLE
Exception when iOS device is inserted

### ISSUE THREAD

**Issue by damonlynch** [damonlynch/rapid-photo-downloader#17]
```
2020-12-13 21:30:56 ERROR excepthook.py 164: An unhandled exception occurred
2020-12-13 21:30:56 ERROR excepthook.py 165: Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/raphodo/storage.py", line 1654, in volumeAdded
    if self.unixDevicePathIsCamera(device_path):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/raphodo/storage.py", line 1378, in unixDevicePathIsCamera
    return self.possibleCamera.search(devname) is not None and udev_is_camera(devname)
TypeError: expected string or bytes-like object
```

**Comment by damonlynch** [comment]
Issue was fixed some time ago but forgot to close this issue
