### ISSUE TITLE
Video download has been broken

### ISSUE THREAD

**Issue by Cimpaci** [damonlynch/rapid-photo-downloader#182]
When I would like to download a video from my camera, Panasonic DMC-FZ200, the downloading starts at first with 7MB/sec till the process bar reach at 95% and it stops. The image downloading works without any issues.Few months ago the video downloading was working in that time. Could someone check this issue? I attached the created log file
[rpd-bug-report-20240331.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/14817381/rpd-bug-report-20240331.tar.gz)

Thanks in advance,
Cimpaci

**Comment by damonlynch** [comment]
Nothing stands out in the log files. There are two possibilities we can immediately think of:

1. There is a bug in 0.9.35 related to downloading videos that was fixed in 0.9.36, but I see no evidence of that bug in the log files you shared.
2. If you are downloading directly from a camera (no memory card reader), libgphoto2 (a library from the gphoto2 project) has been having some issues with some brands of camera (mostly Fuji). Panasonic may be affected too, but I'm uncertain.

If you are downloading from a memory card reader, then this needs more investigation.

**Comment by damonlynch** [comment]
Screenshots don't help at all, unfortunately. 

What would help is if you copy the video file somewhere where there are no other video or photos, set Rapid Photo Downloader to download from that location, and then upload the log files after it is failed copying the video, without downloading any other files in the meantime. That way I will know what to focus on in the log files.

**Comment by NFecDe** [comment]
Dear Damon,
first of all: I am big fan and intense user of the RPD. It is the perfect solution to keep photos and video imported in a structured way.
I have the same problem as Cimpaci and I hope I can give you some more information about the error messages etc.

I do use the RPD on Manjaro Linux and I do use the version Manjaro has currently in their repository. This is the version 0.9.35 (one version behind the current).

I started RPD with the verbose option and as soon as it trying the import a video (mp4, mov or so) the following errors are shown in the terminal I used to launch RPD with the --verbose flag:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 1131, in <module>
    rename.run()
  File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 1090, in run
    move_succeeded = self.process_file(rpd_file, download_count)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 918, in process_file
    generation_succeeded = self.generate_names(rpd_file, synchronize_raw_jpg)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 777, in generate_names
    generate_subfolder(
  File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 275, in generate_subfolder
    rpd_file.download_subfolder = _generate_name(
                                  ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 237, in _generate_name
    do_generation = load_metadata(
                    ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/raphodo/renameandmovefile.py", line 202, in load_metadata
    if rpd_file.metadata is None and not rpd_file.load_metadata(
                                         ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Video.load_metadata() got an unexpected keyword argument 'force_exiftool'

```
I also launched the RPD with the debug and verbose flag and when it came to the problem, a log was created which I share as attachment here (shortened it a little bit to remove some personal data in file names from earlier imports). As I was able to see, it contains more details about the error.

[rpd-bug-report-20240405.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/14882004/rpd-bug-report-20240405.tar.gz)

The issue has to be something about reading meta data from videos. It was working in the past, but I cannot remember until when.
The Manjaro RPD package was realease in January 2024 and since them it is on my system, but I am not sure if I imported since them videos. (I am mainly taking pictures with my digital cameras).

If you have any ideas or I shall try something let me know. 

Thanks a lot for everything!!

KR
Nicolas

**Comment by damonlynch** [comment]
Dear Nicholas,

Thank you for your kind words.

The bug fix for the problem you are seeing was incorporated in 0.9.36. I very much encourage you to request the packager in Manjaro to update the Manjaro package. The best way to do that will probably be to open an issue on the Manjaro bug tracker.

Damon

**Comment by polandy** [comment]
Hello @NFecDe 
I had the same issue on Arch Linux and with release 0.9.36, it is now fixed (Using Fujifilm).
The package in the Arch Linux repository is also outdated (0.9.35). I was able to install the current release 0.9.36 by installing the package `aur/rapid-photo-downloader-git` and adjusting the PKGBUILD; perhaps you can do the same.

- I use yay: `yay rapid photo downloader --editmenu` --> edit pkgbuild
- In source, refer to the tag: `source=('git+https://github.com/damonlynch/rapid-photo-downloader.git#tag=v0.9.36')`

@damonlynch thank you for the great software. Really appreciate it!

KR
Andy

**Comment by bweigel** [comment]
This is related / a duplicate of #135, #125
