### ISSUE TITLE
HEIC preview is broken

### ISSUE THREAD

**Issue by psychosis448** [damonlynch/rapid-photo-downloader#228]
Hello,

I'm currently encountering some error while trying to get the previews for `HEIC` files working.

I got exiftool 12.84 installed.

```log
ERROR    Exception working on file /run/user/1000/rpd-tmp-00008120-001A05E83AD8201E/DCIM/100APPLE/IMG_0158.HEIC
ERROR    Task: ExtractionTask.load_heif_and_exif_directly
ERROR    Processing tasks: {<ExtractionProcessing.resize: 1>}
ERROR    Traceback:
Traceback (most recent call last):
  File "/nix/store/1fx2350i7rj866gh5fg33d3pqshyzkll-rapid-photo-downloader-0.9.34/lib/python3.11/site-packages/raphodo/thumbnailextractor.py", line 686, in process_files
    thumbnail, orientation = self.extract_thumbnail(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/1fx2350i7rj866gh5fg33d3pqshyzkll-rapid-photo-downloader-0.9.34/lib/python3.11/site-packages/raphodo/thumbnailextractor.py", line 580, in extract_thumbnail
    thumbnail = load_heif(
                ^^^^^^^^^^
  File "/nix/store/1fx2350i7rj866gh5fg33d3pqshyzkll-rapid-photo-downloader-0.9.34/lib/python3.11/site-packages/raphodo/heif.py", line 85, in load_heif
    image = pyheif.read_heif(full_file_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/yz1sjm6pgf1qp17dfp38vcwqcjyq2m3j-python3.11-pyheif-0.7.1/lib/python3.11/site-packages/pyheif/reader.py", line 94, in read_heif
    return read(fp, apply_transformations=apply_transformations)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/yz1sjm6pgf1qp17dfp38vcwqcjyq2m3j-python3.11-pyheif-0.7.1/lib/python3.11/site-packages/pyheif/reader.py", line 103, in read
    return heif_file.load()
           ^^^^^^^^^^^^^^^^
  File "/nix/store/yz1sjm6pgf1qp17dfp38vcwqcjyq2m3j-python3.11-pyheif-0.7.1/lib/python3.11/site-packages/pyheif/reader.py", line 47, in load
    self.data, self.stride = _read_heif_image(self._heif_handle, self)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/yz1sjm6pgf1qp17dfp38vcwqcjyq2m3j-python3.11-pyheif-0.7.1/lib/python3.11/site-packages/pyheif/reader.py", line 402, in _read_heif_image
    p_options.ignore_transformations = int(not heif_file.apply_transformations)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ffi.error: struct heif_decoding_options: wrong total size (cdef says 48, but C compiler says 72). fix it or use "...;" as the last field in the cdef for struct heif_decoding_options to make it flexible
```

**Comment by damonlynch** [comment]
That's a bug in [pyheif](https://github.com/carsales/pyheif). It looks like the project needs new contributors or possibly a new maintainer.

**Comment by damonlynch** [comment]
When Rapid Photo Downloader makes the transition from PyQt5 to PyQt6, heif thumbnailing will be possible again. `pyheif` is no longer maintained. The replacement requires PyQt6.
