### ISSUE TITLE
Hangs during Thumbnail-Extractor 5

### ISSUE THREAD

**Issue by brian2drifter** [damonlynch/rapid-photo-downloader#238]
Linux Mint 22 - Kernel 6.8.0-49 RPD 0.9.36

Program hangs during start-up at Thumbnail-Extractor-5

Not used it for a couple of months. Yesterday I cloned the OS onto a larger SSD but everything else works well so the cloning ought not be part of the problem? Interestingly not getting automatic thumbnails in  Nemo (but if open photo and close then it is thumbnailed.

Output from starting RPL via shell with --debug option and crtl-C during hang

`DEBUG: Thumbnail-Extractor-5 worker started
^CTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 875, in <module>
    thumbnail_extractor = ThumbnailExtractor()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 875, in <module>
                          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 184, in __init__
    super().__init__("Thumbnail Extractor")
  File "/usr/lib/python3/dist-packages/raphodo/interprocess.py", line 1162, in __init__
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 875, in <module>
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 875, in <module>
    self.do_work()
    thumbnail_extractor = ThumbnailExtractor()
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 863, in do_work
                          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 184, in __init__
    super().__init__("Thumbnail Extractor")
    self.process_files()
    thumbnail_extractor = ThumbnailExtractor()
    thumbnail_extractor = ThumbnailExtractor()
  File "/usr/lib/python3/dist-packages/raphodo/interprocess.py", line 1162, in __init__
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 642, in process_files
                          ^^^^^^^^^^^^^^^^^^^^
                          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 184, in __init__
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 184, in __init__
    super().__init__("Thumbnail Extractor")
    super().__init__("Thumbnail Extractor")
    directive, content = self.requester.recv_multipart()
  File "/usr/lib/python3/dist-packages/raphodo/interprocess.py", line 1162, in __init__
  File "/usr/lib/python3/dist-packages/raphodo/interprocess.py", line 1162, in __init__
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/zmq/sugar/socket.py", line 729, in recv_multipart
    self.do_work()
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 863, in do_work
    parts = [self.recv(flags, copy=copy, track=track)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/socket.pyx", line 809, in zmq.backend.cython.socket.Socket.recv
    self.do_work()
    self.do_work()
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 863, in do_work
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 863, in do_work
    self.process_files()
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 642, in process_files
  File "zmq/backend/cython/socket.pyx", line 845, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 194, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
    directive, content = self.requester.recv_multipart()
KeyboardInterrupt
    self.process_files()
    self.process_files()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/zmq/sugar/socket.py", line 729, in recv_multipart
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 642, in process_files
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 642, in process_files
    directive, content = self.requester.recv_multipart()
    directive, content = self.requester.recv_multipart()
    parts = [self.recv(flags, copy=copy, track=track)]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/zmq/sugar/socket.py", line 729, in recv_multipart
  File "/usr/lib/python3/dist-packages/zmq/sugar/socket.py", line 729, in recv_multipart
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/socket.pyx", line 809, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 845, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 194, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
    parts = [self.recv(flags, copy=copy, track=track)]
    parts = [self.recv(flags, copy=copy, track=track)]
KeyboardInterrupt
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/socket.pyx", line 809, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 809, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 845, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 845, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 194, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/socket.pyx", line 194, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 875, in <module>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/raphodo/thumbloadbalancer.py", line 52, in <module>
    loadbalancer = ThumbnailLoadBalancer()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/raphodo/thumbloadbalancer.py", line 48, in __init__
    super().__init__("Thumbnail", ThumbnailLoadBalancerWorkerManager)
  File "/usr/lib/python3/dist-packages/raphodo/interprocess.py", line 638, in __init__
    thumbnail_extractor = ThumbnailExtractor()
                          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 184, in __init__
    ioloop.IOLoop.instance().start()
  File "/usr/lib/python3/dist-packages/tornado/platform/asyncio.py", line 205, in start
    super().__init__("Thumbnail Extractor")
  File "/usr/lib/python3/dist-packages/raphodo/interprocess.py", line 1162, in __init__
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/raphodo/thumbnaildaemon.py", line 224, in <module>
    self.do_work()
    self._run_once()
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 863, in do_work
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    generate_thumbnails.run()
  File "/usr/lib/python3/dist-packages/raphodo/thumbnaildaemon.py", line 98, in run
Traceback (most recent call last):
    directive, content = self.receiver.recv_multipart()
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 875, in <module>
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/zmq/sugar/socket.py", line 729, in recv_multipart
    self.process_files()
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 642, in process_files
    parts = [self.recv(flags, copy=copy, track=track)]
    event_list = self._selector.select(timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    directive, content = self.requester.recv_multipart()
  File "zmq/backend/cython/socket.pyx", line 809, in zmq.backend.cython.socket.Socket.recv
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    thumbnail_extractor = ThumbnailExtractor()
  File "/usr/lib/python3.12/selectors.py", line 468, in select
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/zmq/sugar/socket.py", line 729, in recv_multipart
                          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 184, in __init__
  File "zmq/backend/cython/socket.pyx", line 845, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 194, in zmq.backend.cython.socket._recv_copy
    fd_event_list = self._selector.poll(timeout, max_ev)
    super().__init__("Thumbnail Extractor")
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/raphodo/interprocess.py", line 1162, in __init__
KeyboardInterrupt
KeyboardInterrupt
    parts = [self.recv(flags, copy=copy, track=track)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/socket.pyx", line 809, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 845, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 194, in zmq.backend.cython.socket._recv_copy
    self.do_work()
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 863, in do_work
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt
    self.process_files()
  File "/usr/lib/python3/dist-packages/raphodo/thumbnailextractor.py", line 642, in process_files
    directive, content = self.requester.recv_multipart()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/zmq/sugar/socket.py", line 729, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/socket.pyx", line 809, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 845, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 194, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt
ERROR: Encountered problem when closing long-running ExifTool process
ERROR: Encountered problem when closing long-running ExifTool process
ERROR: Encountered problem when closing long-running ExifTool process
ERROR: Encountered problem when closing long-running ExifTool process
ERROR: Encountered problem when closing long-running ExifTool process
ERROR: Encountered problem when closing long-running ExifTool process
^C

`

**Comment by damonlynch** [comment]
I can only wonder if something has gone wrong with the cloning. This is not expected behaviour.

**Comment by brian2drifter** [comment]
Damon

Weird - absolutely everything else appeared to work after cloning. Anyway I
did a clean reinstall just in case and lo Rapid-Photo-Downloader now
appears to be working once again. There are a couple of warnings during the
install re invalid escape sequences from a couple of the easygui/boxes/
modules and /usr/lib/python3/dist-packages/showinfm/system/linux.py but I
guess those are out of your control.

Thanks for the prompt response and sorry it was probably a user error. But
whilst I am in communication can I say THANK YOU for such a great bit of
software. I use it as the example of one of the few Linux apps which are
head and shoulders above anything available on Windows. Thanks again for
your hard work and support.

Brian

**Comment by damonlynch** [comment]
Thank you very much for your kind words Brian. Unfortunately I have not been able to work on the program for some time due to serious health issues.
