### ISSUE TITLE
Failure to Launch: Python 3.10 + Xmonad

### ISSUE THREAD

**Issue by etrigan63** [damonlynch/rapid-photo-downloader#44]
Description: Application fails to launch with Python 3.10 + XMonad.

Additional info:
* 0.9.27-2
* config and/or log files etc.
$ rapid-photo-downloader
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/showinfm/system/linux.py", line 784, in linux_desktop
return LinuxDesktop[env]
File "/usr/lib/python3.10/enum.py", line 440, in __getitem__
return cls._member_map_[name]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/rapid-photo-downloader", line 33, in <module>
sys.exit(load_entry_point('rapid-photo-downloader==0.9.27', 'gui_scripts', 'rapid-photo-downloader')())
File "/usr/bin/rapid-photo-downloader", line 25, in importlib_load_entry_point
return next(matches).load()
File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
module = import_module(match.group('module'))
File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/usr/lib/python3.10/site-packages/raphodo/rapid.py", line 147, in <module>
from raphodo.folderpreviewmanager import FolderPreviewManager
File "/usr/lib/python3.10/site-packages/raphodo/folderpreviewmanager.py", line 30, in <module>
from raphodo.folderspreview import FoldersPreview, DownloadDestination
File "/usr/lib/python3.10/site-packages/raphodo/folderspreview.py", line 47, in <module>
import raphodo.generatename as gn
File "/usr/lib/python3.10/site-packages/raphodo/generatename.py", line 40, in <module>
from raphodo.preferences import DownloadsTodayTracker
File "/usr/lib/python3.10/site-packages/raphodo/preferences.py", line 287, in <module>
class Preferences:
File "/usr/lib/python3.10/site-packages/raphodo/preferences.py", line 294, in Preferences
photo_download_folder=platform_photos_directory(),
File "/usr/lib/python3.10/site-packages/raphodo/storage.py", line 530, in platform_photos_directory
if linux_desktop() == LinuxDesktop.wsl2:
File "/usr/lib/python3.10/site-packages/showinfm/system/linux.py", line 786, in linux_desktop
raise Exception("The desktop environment {} is unknown".format(env))
Exception: The desktop environment is unknown
* link to upstream bug report, if any

Steps to reproduce:
Install RPD on an Xmonad system
Launch RPD
Enjoy the fireworks as it explodes on the launchpad.

**Comment by damonlynch** [comment]
Looks like you're running in a desktop environment that fails to define XDG_CURRENT_DESKTOP. I didn't realize that was possible these days. Who packaged or built your Linux desktop —  you, or the XMonad packager?

**Comment by oz** [comment]
Hi!
I may have found a similar issue with the i3 window manager (Archlinux, [package infos](https://archlinux.org/packages/community/any/rapid-photo-downloader/)).

Here's the traceback at startup:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/showinfm/system/linux.py", line 784, in linux_desktop
    return LinuxDesktop[env]
  File "/usr/lib/python3.10/enum.py", line 440, in __getitem__
    return cls._member_map_[name]
KeyError: 'i3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sbin/rapid-photo-downloader", line 33, in <module>
    sys.exit(load_entry_point('rapid-photo-downloader==0.9.27', 'gui_scripts', 'rapid-photo-downloader')())
  File "/sbin/rapid-photo-downloader", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/raphodo/rapid.py", line 147, in <module>
    from raphodo.folderpreviewmanager import FolderPreviewManager
  File "/usr/lib/python3.10/site-packages/raphodo/folderpreviewmanager.py", line 30, in <module>
    from raphodo.folderspreview import FoldersPreview, DownloadDestination
  File "/usr/lib/python3.10/site-packages/raphodo/folderspreview.py", line 47, in <module>
    import raphodo.generatename as gn
  File "/usr/lib/python3.10/site-packages/raphodo/generatename.py", line 40, in <module>
    from raphodo.preferences import DownloadsTodayTracker
  File "/usr/lib/python3.10/site-packages/raphodo/preferences.py", line 287, in <module>
    class Preferences:
  File "/usr/lib/python3.10/site-packages/raphodo/preferences.py", line 294, in Preferences
    photo_download_folder=platform_photos_directory(),
  File "/usr/lib/python3.10/site-packages/raphodo/storage.py", line 530, in platform_photos_directory
    if linux_desktop() == LinuxDesktop.wsl2:
  File "/usr/lib/python3.10/site-packages/showinfm/system/linux.py", line 786, in linux_desktop
    raise Exception("The desktop environment {} is unknown".format(env))
Exception: The desktop environment i3 is unknown
```

**Comment by etrigan63** [comment]
I worked around it by adding
export XDG_CURRENT_DESKTOP=xfce to /etc/environment and rebooted. The code needs to account for that being blank, but this will let us keep using it until the patch arrives.

--

**Comment by damonlynch** [comment]
@etrigan63 Who packaged or built your Linux desktop — you, or the XMonad packager?

**Comment by etrigan63** [comment]
Arcolinux packaged this.

--

**Comment by etrigan63** [comment]
Still, RPD should detect this and at least gracefully exit, not crash and burn.

--

**Comment by damonlynch** [comment]
> Still, RPD should detect this and at least gracefully exit, not crash and burn.

That is correct. In many programs, a huge proportion of developer time is spent dealing with edge cases and unusual setups.

**Comment by etrigan63** [comment]
Many tiling window managers suffer from this. However a lot of them use "xfce" tools and utilities. Perhaps defaulting to "xfce" if it is blank or unexpected would be better?

**Comment by damonlynch** [comment]
The primary point of determining the desktop is to solve certain problems that only come up on a few desktops. XFCE is not one of them. A secondary purpose is to determine the default file manager, which is useful when it has been set incorrectly for the user, e.g. to an AppImage.

**Comment by purew** [comment]
`XDG_CURRENT_DESKTOP` is not required to be set according to https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html AFAICT.

I also started getting this failure on latest Archlinux with i3 window manager (built and packaged by archlinux).

**Comment by damonlynch** [comment]
Arch doesn't have 0.9.28 yet?

The XDG specs are not perfectly written. Like anything they contain oversights and omissions.  It is customary for `XDG_CURRENT_DESKTOP` to be declared, so _almost_ every desktop declares it. Those that don't have few users so the issue doesn't come up much. An ambiguity exists for window managers which by their nature are not full desktops. This is an unfortunate aspect of the spec.

**Comment by purew** [comment]
> Arch doesn't have 0.9.28 yet?

Not yet, it's marked at out-of-date at https://archlinux.org/packages/community/any/rapid-photo-downloader/ but the community packages sometimes takes a bit longer to update.

**Comment by lennie420** [comment]
I feel like I'm having the exact issue on Sway window manager on Arch Linux. The program errors out and says it is unable to process anything even though it shows the thumbnails.

For what it's worth I am able to properly import photos with Shotwell and Darktable.
