### ISSUE TITLE
rapid-photo-downloader crashes on startup

### ISSUE THREAD

**Issue by Sk4zz** [damonlynch/rapid-photo-downloader#79]
I'm running Manjaro i3 with kernel 5.15.49-1-MANJARO

```
** (process:116445): WARNING **: 17:13:20.413: Failed to load shared library 'libdee-1.0.so.4' referenced by the typelib: libicui18n.so.70: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/rapid-photo-downloader", line 33, in <module>
    sys.exit(load_entry_point('rapid-photo-downloader==0.9.33', 'gui_scripts', 'rapid-photo-downloader')())
  File "/usr/bin/rapid-photo-downloader", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/raphodo/rapid.py", line 75, in <module>
    from gi.repository import Unity
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/usr/lib/python3.10/site-packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/usr/lib/python3.10/site-packages/gi/importer.py", line 150, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.10/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/gi/overrides/Dee.py", line 53, in <module>
    class Model(Dee.Model):
  File "/usr/lib/python3.10/site-packages/gi/module.py", line 207, in __getattr__
    wrapper = metaclass(name, bases, dict_)
  File "/usr/lib/python3.10/site-packages/gi/types.py", line 247, in __init__
    register_interface_info(cls.__info__.get_g_type())
TypeError: must be an interface
```
Dee seems to be installed alright
```
❯ sudo find / -name libdee-1.0.so.4
/usr/lib/libdee-1.0.so.4
```

**Comment by damonlynch** [comment]
This very much looks like a bug in Manjaro. I strongly suggest taking it up with the Manjaro project. If I'm wrong, do let me know. But it has the classic hallmarks of a distribution bug.
