### ISSUE TITLE
Failing to start due to `ValueError: Namespace Notify not available for version 0.7`

### ISSUE THREAD

**Issue by purew** [damonlynch/rapid-photo-downloader#81]
I'm running Archlinux, `rapid-photo-downloader` installed from the community repo. I've used this program for many years but today when trying to start the program, I'm greeted by the following

```
$ rapid-photo-downloader
Traceback (most recent call last):
  File "/usr/bin/rapid-photo-downloader", line 33, in <module>
    sys.exit(load_entry_point('rapid-photo-downloader==0.9.33', 'gui_scripts', 'rapid-photo-downloader')())
  File "/usr/bin/rapid-photo-downloader", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/raphodo/rapid.py", line 70, in <module>
    gi.require_version("Notify", "0.7")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Notify not available for version 0.7
```

Not really sure what this means, but I assume some dependency has been upgraded and something in rapid-photo-downloader must be updated?

**Comment by purew** [comment]
Yup, I edited `/usr/lib/python3.10/site-packages/gi/__init__.py` to print the available versions, and it prints `0.8` while `rapid-photo-downloader` requests `0.7`.

**Comment by purew** [comment]
And, indeed, editing `rapid.py` to request 0.8 instead of 0.7 allows me to start the program :tada:

**Comment by damonlynch** [comment]
Looks like it was fixed upstream https://gitlab.gnome.org/GNOME/libnotify/-/commit/650f2f123e75469b85d81fbca66e17b744a7714b
